### ISSUE TITLE
findDOMNode exploding with react 15

### ISSUE THREAD

**Issue by gavmck** [Legitcode/scheduler#20]
Getting

```
Uncaught (in promise) Error: traverseParentPath(....): Cannot traverse from and to the same ID, ``.
```

Caused by findDOMNode in Cell.jsx

Looks like replacing it with an element ref should fix it?

**Comment by dphaener** [comment]
@gavmck That's possible. This entire component really needs some work to be fully compliant with 15.x.x. Want to take a crack at it? I probably won't have time to look at it in depth for a few days...

**Comment by zackify** [comment]
This might work correctly, don't have time to pull it down tho https://github.com/Legitcode/scheduler/pull/21

**Comment by gavmck** [comment]
Smashed in a pull request. Few warnings on propTypes validation, but seems to be working.

**Comment by dphaener** [comment]
@gavmck 0.3.0 released. Thanks again! :tada:

**Comment by gavmck** [comment]
Awesome! 💯
