### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by bytewiz** [Legitcode/scheduler#23]

**Comment by zackify** [comment]
Not actively, but @dphaener may still be using it. We will accept PR's if there's anything you want to add.

**Comment by bytewiz** [comment]
@zackify cool 👍 thanks for very instant reply! 🎉

**Comment by dphaener** [comment]
@bytewiz I definitely respond to bug reports as much as I can, but I am not building new features at this time. I haven't abandoned it completely. I originally wrote it to replace Full Calendar in one of my apps and haven't had a need to upgrade it beyond where it's at now. But like @zackify said I am definitely open to PR's for sure!

**Comment by bytewiz** [comment]
@dphaener awesome!
