### ISSUE TITLE
Example problem

### ISSUE THREAD

**Issue by JD2k** [Legitcode/scheduler#24]
Hello,

i tried to use this component. But if i just copy the example i got some import problems.

It seems that the objects are not correct imported.

I did the import like this:

`import Scheduler from 'legit-scheduler'`
`import RangeDate from 'legit-scheduler'`
`import DateRange from 'legit-scheduler'`

And get for the example the error code:

> TypeError: from.advance is not a function

Even if i get rid from RangeDate and DateRange import the calender gets roughly rendered but throws this error:

>  TypeError: Cannot read property 'getHeaderColGrouop' of undefined

Modules:

"react": "^15.3.2",
"legit-scheduler": "^0.3.0"

Can someone help me out here?

**Comment by JD2k** [comment]
Fortunately i got it solved. Copied the whole source and rewrote it in ES6 Syntax since Phpstorm unfortunately can't use ES7. Thx for this component. Saving me a lot of time :)

**Comment by dphaener** [comment]
@JD2k Sorry I didn't get back to you on this! Glad you solved it!

**Comment by t-hughes** [comment]
@JD2k Can you share that file you solved?

**Comment by JD2k** [comment]
@t-hughes Unfortunately not because i changed every file and in the meantime i changed nearly everything to fit for my needs. But this example should work with any other editor which supports ES7.
