### ISSUE TITLE
TypeError: _react.PropTypes is undefined

### ISSUE THREAD

**Issue by camux** [Legitcode/scheduler#30]
I am using this lib, but I am getting this error

TypeError: _react.PropTypes is undefined
./node_modules/legit-scheduler/lib/event.js
node_modules/legit-scheduler/lib/event.js:198

  195 | 
  196 |   return Event;
  197 | }(_react2.default.Component), _class2.propTypes = {
> 198 |   title: _react.PropTypes.string.isRequired,
  199 |   startDate: _react.PropTypes.string.isRequired,
  200 |   duration: _react.PropTypes.number.isRequired,
  201 |   resource: _react.PropTypes.string.isRequired,

my package.json

{
  "name": "react-flask-hotel",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "legit-scheduler": "^0.3.1",
    "material-ui": "^0.20.0",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-flexbox-grid": "^2.0.0"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.24.1",
    "react-scripts": "1.1.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

**Comment by logart** [comment]
Same here! I've submitted a pull request a week before that works for me locally but it seems that npm uses old version.
Does anybody know how to check which version is deployed in npm?

**Comment by dphaener** [comment]
Hey there. So sorry about this. I apparently forgot how to npm. :) The package was not actually built before release. I thought I had a pre publish hook in there but I did not. I'm working on building and releasing a new version right now.

**Comment by dphaener** [comment]
Ok just published 0.3.2 and yanked 0.3.1 as it's completely broken. Sorry again!

**Comment by camux** [comment]
Thanks solved!
