### ISSUE TITLE
Support for different day based ranges

### ISSUE THREAD

**Issue by YanivRan** [Legitcode/scheduler#6]
Right now the scheduler is hard set on a 4 weeks (in days) for display. It would be nice to have it more flexible. It would be nice to be able to send a start date, and end date and get a table that is showing the right range (right now it will distort the entire table).

**Comment by dphaener** [comment]
Thanks for the feedback. Someone is actually working on this right now, though I'm not sure how long it will be. A PR is welcome, otherwise, it may be awhile. I'm pretty busy on things that are paying me right now. :)

**Comment by dphaener** [comment]
Ok so @zackify guilted me into fixing this. :) As of https://github.com/Legitcode/scheduler/commit/58b2280586f079876beb58b7ee6c524cd7213022 the scheduler now supports this. It wasn't a big change at all. Version 0.2.0 has been released.

The scheduler will now accept whatever date range you give it, and will advance/retard the date range according to the number of days in date range you give it.

@YanivRan
